version: "3.7"

services:
  api:
    container_name: todos_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:8081
    environment: 
      - GO_ENV=production
      - DB_HOST=svr-aura.luqmanul.com
      - DB_PORT=5555
      - DB_USER=hakim
      - DB_PASS=masuk123
      - DB_SCHEMA=todos
      - DB_PATH=public