version: "3.7"

services:
  db:
    container_name: todos_db
    image: postgres:alpine
    restart: always
    networks:
    - todosnet
    volumes:
      - ./_DATA/:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=hakim
      - POSTGRES_PASSWORD=masuk123
      - POSTGRES_DB=todos
    
  api:
    container_name: todos_api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:8081
    networks: 
      - todosnet
    depends_on:
      - db
    command: sleep 5
    environment: 
      - GO_ENV=production
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=hakim
      - DB_PASS=masuk123
      - DB_SCHEMA=todos
      - DB_PATH=public

networks: 
  todosnet:
    driver: bridge